numandev1/react-native-compressor

- example/ios/Podfile.lock
- example/src/Screens/Video/index.tsx
- package.json
- src/Video/index.tsx
- src/index.tsx
- src/utils/index.tsx
- yarn.lock
fixed #60 #61 
fix: UUID issue by making js base uuid
> fix: uuid issue by making js base uuid

- example/src/Screens/Video/index.tsx
- ios/Video/VideoCompressor.swift
> fix: crash due to remeasured bitrate in ios fixed #63

- README.md
- android/build.gradle
- android/src/main/java/com/reactnativecompressor/Audio/AudioCompressor.java
- android/src/main/java/com/reactnativecompressor/CompressorModule.java
- android/src/main/java/com/reactnativecompressor/Utils/Utils.java
- android/src/main/java/com/reactnativecompressor/Video/AutoVideoCompression/AutoVideoCompression.java
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressorHelper.java
- android/src/main/java/com/reactnativecompressor/Video/VideoModule.java
- android/src/main/java/com/reactnativecompressor/Video/videoslimmer/VideoSlimEncoder.java
- android/src/main/java/com/reactnativecompressor/Video/videoslimmer/VideoSlimTask.java
- android/src/main/java/com/reactnativecompressor/Video/videoslimmer/VideoSlimmer.java
- android/src/main/java/com/reactnativecompressor/Video/videoslimmer/listner/SlimProgressListener.java
- android/src/main/java/com/reactnativecompressor/Video/videoslimmer/muxer/CodecInputSurface.java
- android/src/main/java/com/reactnativecompressor/Video/videoslimmer/render/TextureRenderer.java
- example/src/Screens/Video/index.tsx
- ios/Compressor.m
- ios/Video/VideoCompressor.swift
- src/Video/index.tsx
> feat: add cancellation compression in IOS and android

- README.md
- android/build.gradle
- example/android/settings.gradle
- package.json
fixed #79
[CATEGORY] [TYPE] - Message
> fix: sound of compressed video

- example/ios/CompressorExample/Info.plist
- example/ios/Podfile.lock
- example/package.json
- example/src/Screens/Image/index.tsx
- example/src/Screens/Video/index.tsx
- example/yarn.lock
- ios/Compressor-Bridging-Header.h
- ios/Compressor.m
- ios/Image/ImageCompressor.h
- ios/Image/ImageCompressor.m
- ios/Video/VideoCompressor.swift
> feat: add ph file support for video/image due to cameraroll (ph://)

- README.md
- android/src/main/java/com/reactnativecompressor/CompressorModule.java
- example/src/Components/Button.tsx
- example/src/Screens/Util/index.tsx
- example/src/Screens/index.tsx
- ios/Compressor.m
- ios/Image/ImageCompressor.m
- src/index.tsx
- src/utils/index.tsx
> feat: add getVideoMetaData function for video metadata

- README.md
> docs: update table of content

- android/build.gradle
> fix: #117 build issue on android

- android/src/main/java/com/reactnativecompressor/Utils/Utils.java
fix android compressVideo onFinish and onError path
> fix android compressVideo path

- android/build.gradle
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressorHelper.java
- lefthook.yml
fixed https://github.com/numandev1/react-native-compressor/issues/108
> chore: fix: manual compression bitrate and maxsize issue

- README.md
- android/src/main/java/com/reactnativecompressor/Image/ImageCompressor.java
- example/src/Screens/Image/index.tsx
may fixed https://github.com/numandev1/react-native-compressor/issues/114
> fix: image orientation

- README.md
- example/ios/CompressorExample.xcodeproj/project.pbxproj
- example/ios/Podfile.lock
- example/src/Screens/Video/index.tsx
- ios/Video/VideoCompressor.swift
fixed https://github.com/numandev1/react-native-compressor/issues/107
> fix: manual video compression

- android/build.gradle
- android/src/main/java/com/reactnativecompressor/Audio/AudioCompressor.kt
- android/src/main/java/com/reactnativecompressor/Utils/Utils.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/CompressionInterface.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/VideoCompressorClass.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/compressor/Compressor.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/utils/Atoms.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/utils/CompressorUtils.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/utils/NumbersUtils.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/utils/StreamableVideo.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/videoHelpers/InputSurface.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/videoHelpers/MP4Builder.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/videoHelpers/Mdat.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/videoHelpers/Mp4Movie.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/videoHelpers/OutputSurface.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/videoHelpers/Result.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/videoHelpers/Sample.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/videoHelpers/TextureRenderer.kt
- android/src/main/java/com/reactnativecompressor/Video/VideoCompressor/videoHelpers/Track.kt
fixed https://github.com/numandev1/react-native-compressor/issues/125
> fix: increase speed of android video compression

- android/src/oldarch/CompressorSpec.kt
- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
fixed https://github.com/numandev1/react-native-compressor/issues/182
> fix: a failure occurred while executing kotlin.compilerRunner

- example/ios/Podfile.lock
- src/utils/index.tsx
fixed https://github.com/numandev1/react-native-compressor/issues/102
> fix: get real path type

- ios/Image/ImageCompressorOptions.swift
fixed https://github.com/numandev1/react-native-compressor/issues/189
> fix: image manual compression

- README.md
- android/build.gradle
- android/src/main/java/com/reactnativecompressor/Audio/AudioCompressor.kt
- android/src/main/java/com/reactnativecompressor/Audio/AudioHelper.kt
- android/src/main/java/com/reactnativecompressor/Audio/AudioMain.kt
- android/src/main/java/com/reactnativecompressor/Utils/RealPathUtil.kt
- android/src/main/java/com/reactnativecompressor/Utils/Utils.kt
- example/src/Screens/Audio/index.tsx
- src/Audio/index.tsx
- src/utils/index.tsx
fixed https://github.com/numandev1/react-native-compressor/issues/177 https://github.com/numandev1/react-native-compressor/issues/172
> fix: android audio compression

- README.md
- android/build.gradle
- android/src/main/java/com/reactnativecompressor/Audio/AudioCompressor.kt
- android/src/main/java/com/reactnativecompressor/Audio/AudioExtractor.kt
- android/src/main/java/com/reactnativecompressor/Audio/AudioMain.kt
fixed https://github.com/numandev1/react-native-compressor/issues/172
> fix: audio wav and mp4 audio and bypass if fail

- android/build.gradle
fixed https://github.com/numandev1/react-native-compressor/issues/198
> fix: compile error on android due to coreprogress

- README.md
- android/src/main/java/com/reactnativecompressor/Image/ImageCompressor.kt
- example/ios/Podfile.lock
- ios/Image/ImageCompressor.swift
fixed https://github.com/numandev1/react-native-compressor/issues/201
> fix: mime type and quality for umage png output

- README.md
- android/src/main/java/com/reactnativecompressor/Image/ImageCompressor.kt
- android/src/main/java/com/reactnativecompressor/Image/ImageCompressorOptions.kt
- example/ios/Podfile.lock
- ios/Image/ImageCompressor.swift
- ios/Image/ImageCompressorOptions.swift
- src/Image/index.tsx
fixed https://github.com/numandev1/react-native-compressor/issues/206
> fix: png transparent background

- src/utils/Uploader.tsx
fixed https://github.com/numandev1/react-native-compressor/issues/223
> fix: uuid error when user try to upload

- android/src/main/java/com/reactnativecompressor/Utils/Utils.kt
- example/ios/CompressorExample.xcodeproj/project.pbxproj
- example/ios/Gemfile
- example/ios/Gemfile.lock
- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- ios/Image/ImageCompressor.swift
- ios/Utils/Utils.swift
- ios/Video/VideoMain.swift
fixed https://github.com/numandev1/react-native-compressor/issues/222 https://github.com/numandev1/react-native-compressor/issues/221
> fix: absolute path which does not start will file://

- android/src/main/java/com/reactnativecompressor/Utils/Utils.kt
Fixes the hanging promise issue on android that happens when the video compression fails or cancelled by user.
fix 
[CATEGORY] [TYPE] - Message
```
```
> fix(compressVideo): reject promise on failure or cancellation

- README.md
- android/src/main/java/com/reactnativecompressor/Utils/createVideoThumbnail.kt
fixed https://github.com/numandev1/react-native-compressor/issues/211
> fix: video compression in background mode

- README.md
- android/src/main/java/com/reactnativecompressor/Utils/createVideoThumbnail.kt
- example/ios/Podfile.lock
- ios/Video/NextLevelSessionExporter.swift
- ios/Video/VideoMain.swift
- react-native-compressor.podspec
fixed https://github.com/numandev1/react-native-compressor/issues/204
> refactor: next level session and add manual linking through pod

- README.md
- android/build.gradle
- android/src/main/java/com/reactnativecompressor/CompressorModule.kt
- android/src/main/java/com/reactnativecompressor/Utils/HttpCallManager.kt
- android/src/main/java/com/reactnativecompressor/Utils/Uploader.kt
- android/src/oldarch/CompressorSpec.kt
- example/ios/CompressorExample.xcodeproj/project.pbxproj
- example/ios/Gemfile.lock
- example/ios/Podfile.lock
- example/src/Screens/Main/index.tsx
- example/src/Screens/Video/index.tsx
- example/src/Screens/index.tsx
- exampleExpo/src/Screens/Main/index.tsx
- exampleExpo/src/Screens/index.tsx
- ios/Compressor.mm
- ios/CompressorManager.swift
- ios/Utils/Uploader.swift
- ios/Utils/UrlTaskManager.swift
- src/Spec/NativeCompressor.ts
- src/index.tsx
- src/utils/Uploader.tsx
related https://github.com/numandev1/react-native-compressor/pull/225
fixed https://github.com/numandev1/react-native-compressor/issues/212
> feat: add cancelUpload and AbortController for backgroundUpload

- ios/Image/ImageCompressor.swift
- in ios some of the images were getting rotated to 90 deg
- used image returned from scaleAndRotate function
> use scaleAndRotate returned image

- ios/Video/NextLevelSessionExporter.swift
fix https://github.com/numandev1/react-native-compressor/issues/322 https://github.com/numandev1/react-native-compressor/issues/323
[CATEGORY] [TYPE] - Message
> fix: cannot find 'kAudioFormatAPAC' in scope

- ios/Video/NextLevelSessionExporter.swift
temp fix for https://github.com/numandev1/react-native-compressor/issues/323 https://github.com/numandev1/react-native-compressor/issues/322
[CATEGORY] [TYPE] - Message
> fix: temporary fix for kAudioFormatAPAC

- src/Image/index.tsx
> Fixed repetition
